parameters:
#    exo_user.example.class: Exo\UserBundle\Example

services:
#    exo_user.example:
#        class: %exo_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
