<?php

namespace Exo\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * InfoProRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InfoProRepository extends EntityRepository
{
}
